package security

import (
	"encoding/json"
	"os"
	"testing"
)

// unlock-cookie golden vectors (Phase 12.5f): the shared file at
// ../../../shared/security/unlock-cookie-vectors.json is generated by the
// Next.js reference (scripts/generate-unlock-cookie-vectors.ts) plus the Go
// tool (test/genvectors). This suite proves the Go implementation reproduces
// every create-parity value byte-for-byte and accepts/rejects every value
// exactly like the reference.

type goldenPayload struct {
	SessionID  string `json:"sessionId"`
	Locale     string `json:"locale"`
	UnlockedAt int64  `json:"unlockedAt"`
}

type goldenVector struct {
	Name         string         `json:"name"`
	CreatedBy    string         `json:"createdBy"`
	Secret       string         `json:"secret"`
	VerifySecret string         `json:"verifySecret"`
	Payload      *goldenPayload `json:"payload"`
	Value        string         `json:"value"`
	ExpectVerify bool           `json:"expectVerify"`
	Note         string         `json:"note"`
}

type goldenDoc struct {
	Description string `json:"description"`
	Spec        struct {
		ValueFormat      string   `json:"valueFormat"`
		PayloadKeyOrder  []string `json:"payloadKeyOrder"`
		CookieAttributes struct {
			Name          string `json:"name"`
			Path          string `json:"path"`
			HTTPOnly      bool   `json:"httpOnly"`
			SameSite      string `json:"sameSite"`
			Secure        string `json:"secure"`
			MaxAgeSeconds int    `json:"maxAgeSeconds"`
		} `json:"cookieAttributes"`
	} `json:"spec"`
	Vectors []goldenVector `json:"vectors"`
}

func loadGoldenVectors(t *testing.T) goldenDoc {
	t.Helper()
	data, err := os.ReadFile("../../../shared/security/unlock-cookie-vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var doc goldenDoc
	if err := json.Unmarshal(data, &doc); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(doc.Vectors) == 0 {
		t.Fatal("no vectors loaded")
	}
	return doc
}

// TestUnlockCookieGoldenVectors proves cross-stack verify semantics: every
// value (Node-minted, Go-minted, and hand-signed negatives) is accepted or
// rejected exactly as the reference dictates.
func TestUnlockCookieGoldenVectors(t *testing.T) {
	doc := loadGoldenVectors(t)
	seenCreators := map[string]bool{}

	for _, v := range doc.Vectors {
		t.Run(v.Name, func(t *testing.T) {
			seenCreators[v.CreatedBy] = true
			secret := v.Secret
			if v.VerifySecret != "" {
				secret = v.VerifySecret
			}
			got := VerifyUnlockCookieValue(v.Value, secret)
			if !v.ExpectVerify {
				if got != nil {
					t.Fatalf("expected rejection, got %+v (note: %s)", got, v.Note)
				}
				return
			}
			if got == nil {
				t.Fatalf("expected acceptance, got nil (note: %s)", v.Note)
			}
			if v.Payload == nil {
				t.Fatal("accepting vector must carry its expected payload")
			}
			if got.SessionID != v.Payload.SessionID ||
				got.Locale != v.Payload.Locale ||
				got.UnlockedAt != v.Payload.UnlockedAt {
				t.Fatalf("payload mismatch: got %+v want %+v", got, *v.Payload)
			}
		})
	}

	// The file must contain vectors minted by BOTH stacks — otherwise it does
	// not prove interop in both directions.
	if !seenCreators["node"] || !seenCreators["go"] {
		t.Fatalf("vectors must include node- and go-created entries: %v", seenCreators)
	}
}

// TestUnlockCookieCreateParity proves byte-exact creation: for every vector
// with a payload, the Go implementation reproduces the stored value exactly —
// same JSON key order, same raw base64url, same HMAC-SHA256 input, no HTML
// escaping — regardless of which stack minted it.
func TestUnlockCookieCreateParity(t *testing.T) {
	doc := loadGoldenVectors(t)
	checked := 0
	for _, v := range doc.Vectors {
		// Only stack-minted vectors are create-parity cases; "manual" vectors
		// (e.g. extra trailing segments) are verify-only by construction.
		if v.Payload == nil || (v.CreatedBy != "node" && v.CreatedBy != "go") {
			continue
		}
		t.Run(v.Name, func(t *testing.T) {
			got := CreateUnlockCookieValue(UnlockPayload{
				SessionID:  v.Payload.SessionID,
				Locale:     v.Payload.Locale,
				UnlockedAt: v.Payload.UnlockedAt,
			}, v.Secret)
			if got != v.Value {
				t.Fatalf("create mismatch:\n got: %s\nwant: %s", got, v.Value)
			}
		})
		checked++
	}
	if checked < 4 {
		t.Fatalf("too few create-parity vectors checked: %d", checked)
	}
}

// TestUnlockCookieSpecAttributes pins the documented cookie attributes so the
// shared file and the Go setter (handler/sentinel.go) cannot drift apart.
func TestUnlockCookieSpecAttributes(t *testing.T) {
	doc := loadGoldenVectors(t)
	a := doc.Spec.CookieAttributes
	if a.Name != "karot_unlock" || a.Path != "/" || !a.HTTPOnly ||
		a.SameSite != "Lax" || a.MaxAgeSeconds != 1209600 || a.Secure == "" {
		t.Fatalf("cookie attributes drifted: %+v", a)
	}
	if got := doc.Spec.PayloadKeyOrder; len(got) != 3 ||
		got[0] != "sessionId" || got[1] != "locale" || got[2] != "unlockedAt" {
		t.Fatalf("payload key order drifted: %v", got)
	}
}
